# Generated by Django 2.0.2 on 2018-02-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20180210_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameturn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='players.Game'),
        ),
        migrations.AlterField(
            model_name='gameturnplay',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='players.GameTurn'),
        ),
    ]
